{{- if and .Values.webhook.enabled .Values.webhook.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "osmia.fullname" . }}-webhook
  labels:
    {{- include "osmia.labels" . | nindent 4 }}
  {{- with .Values.webhook.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.webhook.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.webhook.ingress.tls }}
  tls:
    {{- range .Values.webhook.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webhook.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "osmia.fullname" $ }}-webhook
                port:
                  number: {{ $.Values.webhook.port }}
          {{- end }}
    {{- end }}
{{- end }}
