{{- if .Values.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "osmia.fullname" . }}-webhook
  labels:
    {{- include "osmia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.webhook.port }}
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    {{- include "osmia.selectorLabels" . | nindent 4 }}
{{- end }}
