"""Base class helpers for authoring Osmia gRPC plugins in Python.

Every Osmia plugin is an out-of-process gRPC server. The controller
spawns the plugin binary as a subprocess and negotiates a connection over
the hashicorp/go-plugin transport (stdin/stdout handshake followed by a
local TCP or Unix-socket gRPC channel).

Usage::

    from osmia.plugin import PluginBase
    from osmia.proto import ticketing_pb2_grpc

    class MyPlugin(ticketing_pb2_grpc.TicketingBackendServicer):
        ...

    if __name__ == "__main__":
        PluginBase.serve(MyPlugin())
"""

from __future__ import annotations

import abc
import logging
import os
from concurrent import futures

import grpc

logger = logging.getLogger(__name__)

# Default number of worker threads for the gRPC server.
_DEFAULT_WORKERS = 4


class PluginBase(abc.ABC):
    """Abstract base for Osmia plugin servicers.

    Subclass this (or use it as a mixin alongside a generated gRPC
    servicer class) to get access to the :meth:`serve` convenience
    method.
    """

    @staticmethod
    def serve(servicer: object, *, port: int | None = None, workers: int = _DEFAULT_WORKERS) -> None:
        """Start a blocking gRPC server hosting *servicer*.

        The listening port is taken from the ``OSMIA_PLUGIN_PORT``
        environment variable if *port* is not specified. When neither is
        set the server binds to an ephemeral port on ``127.0.0.1``.

        Args:
            servicer: A gRPC servicer instance generated from the Osmia
                protobuf definitions. Must have an ``add_to_server``
                classmethod (auto-generated by grpcio-tools).
            port: Optional TCP port override. Defaults to the value of the
                ``OSMIA_PLUGIN_PORT`` environment variable, or 0 (ephemeral).
            workers: Number of gRPC thread-pool workers. Defaults to 4.
        """
        if port is None:
            port = int(os.environ.get("OSMIA_PLUGIN_PORT", "0"))

        server = grpc.server(futures.ThreadPoolExecutor(max_workers=workers))

        # Locate and call the generated add_*_to_server helper.
        add_fn_name = f"add_{type(servicer).__name__}_to_server"
        module = __import__(type(servicer).__module__, fromlist=[""])
        add_fn = getattr(module, add_fn_name, None)
        if add_fn is None:
            raise RuntimeError(
                f"could not find {add_fn_name!r} in {type(servicer).__module__!r}; "
                "ensure you are passing a generated gRPC servicer instance"
            )
        add_fn(servicer, server)

        address = f"127.0.0.1:{port}"
        actual_port = server.add_insecure_port(address)
        server.start()
        logger.info("Osmia plugin listening", extra={"port": actual_port})
        server.wait_for_termination()
